# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-03 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('democracy', '0012_add_organization_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='id',
            field=models.CharField(blank=True, help_text='You may leave this empty to automatically generate an ID', max_length=32, primary_key=True, serialize=False, verbose_name='identifier'),
        ),
    ]
